//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.02.25 at 02:50:35 AM CET 
//


package org.openestate.io.immobiliare_it.xml;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for garden.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="garden">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="Privato"/>
 *     &lt;enumeration value="Comune"/>
 *     &lt;enumeration value="Nessuno"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "garden")
@XmlEnum
public enum Garden {

    @XmlEnumValue("Privato")
    PRIVATO("Privato"),
    @XmlEnumValue("Comune")
    COMUNE("Comune"),
    @XmlEnumValue("Nessuno")
    NESSUNO("Nessuno");
    private final String value;

    Garden(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static Garden fromValue(String v) {
        for (Garden c: Garden.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
