//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.03.01 at 03:45:54 AM CET 
//


package org.openestate.io.immobiliare_it.xml;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for heat.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="heat">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="Assente"/>
 *     &lt;enumeration value="Autonomo"/>
 *     &lt;enumeration value="Centralizzato"/>
 *     &lt;enumeration value="Teleriscaldamento"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "heat")
@XmlEnum
public enum Heat {

    @XmlEnumValue("Assente")
    ASSENTE("Assente"),
    @XmlEnumValue("Autonomo")
    AUTONOMO("Autonomo"),
    @XmlEnumValue("Centralizzato")
    CENTRALIZZATO("Centralizzato"),
    @XmlEnumValue("Teleriscaldamento")
    TELERISCALDAMENTO("Teleriscaldamento");
    private final String value;

    Heat(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static Heat fromValue(String v) {
        for (Heat c: Heat.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
