//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.02.25 at 02:50:35 AM CET 
//


package org.openestate.io.immobiliare_it.xml;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for version.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="version">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="1.5"/>
 *     &lt;enumeration value="1.6"/>
 *     &lt;enumeration value="2.0"/>
 *     &lt;enumeration value="2.1"/>
 *     &lt;enumeration value="2.2"/>
 *     &lt;enumeration value="2.4"/>
 *     &lt;enumeration value="2.2.1"/>
 *     &lt;enumeration value="2.5"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "version")
@XmlEnum
public enum Version {

    @XmlEnumValue("1.5")
    V1_5("1.5"),
    @XmlEnumValue("1.6")
    V1_6("1.6"),
    @XmlEnumValue("2.0")
    V2_0("2.0"),
    @XmlEnumValue("2.1")
    V2_1("2.1"),
    @XmlEnumValue("2.2")
    V2_2("2.2"),
    @XmlEnumValue("2.4")
    V2_4("2.4"),
    @XmlEnumValue("2.2.1")
    V2_2_1("2.2.1"),
    @XmlEnumValue("2.5")
    V2_5("2.5");
    private final String value;

    Version(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static Version fromValue(String v) {
        for (Version c: Version.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
